/**
 * Categorization rules and helpers for background analytics.
 */

const CUSTOM_CATEGORY_RULES_KEY = 'customCategoryRules';

/**
 * Domain categorization rules - EXPANDED
 */
const CATEGORY_RULES = {
	development: [
		/^localhost/i,
		/^127\.0\.0\.1/i,
		/^0\.0\.0\.0/i,
		/^192\.168\./i,
		/^10\.\d+\.\d+\.\d+/i,
		/^172\.(1[6-9]|2\d|3[01])\./i,
		/\.local$/i,
		/\.localhost$/i,
		/\.test$/i,
		/\.dev$/i,
		/\.example$/i,
		/ngrok\.io/i,
		/ngrok-free\.app/i,
		/localtunnel\.me/i,
		/localhost\.run/i,
		/loca\.lt/i,
		/vscode\.dev/i,
		/github\.dev/i,
		/codespaces\.github/i,
		/gitpod\.io/i,
		/stackblitz\.com/i,
		/glitch\.com/i,
		/railway\.app/i,
		/render\.com/i,
		/fly\.io/i,
		/supabase\.com/i,
		/supabase\.co/i,
		/firebase\.google/i,
		/firebaseio\.com/i,
		/planetscale\.com/i,
		/neon\.tech/i,
		/upstash\.com/i,
		/mongodb\.com/i,
		/prisma\.io/i,
		/docker\.com/i,
		/hub\.docker/i,
		/kubernetes\.io/i,
		/expo\.dev/i,
		/expo\.io/i,
		/snack\.expo/i,
		/appetize\.io/i,
		/browserstack\.com/i,
		/saucelabs\.com/i,
		/lambdatest\.com/i,
		/cypress\.io/i,
		/playwright\.dev/i,
		/storybook\.js\.org/i,
		/chromatic\.com/i,
		/bit\.dev/i,
		/bundlephobia\.com/i,
		/unpkg\.com/i,
		/jsdelivr\.net/i,
		/cdnjs\.com/i,
		/skypack\.dev/i,
		/esm\.sh/i,
		/deno\.land/i,
		/pkg\.go\.dev/i,
		/crates\.io/i,
		/rubygems\.org/i,
		/nuget\.org/i,
		/maven\.org/i,
		/mvnrepository\.com/i,
		/cocoapods\.org/i,
		/pub\.dev/i,
		/hex\.pm/i,
		/hackage\.haskell/i,
		/pkg\.julialang/i,
		/github\.com/i,
		/gitlab\.com/i,
	],
	work: [
		/bitbucket\.org/i,
		/clockify\.me/i,
		/stackoverflow\.com/i,
		/stackexchange\.com/i,
		/slack\.com/i,
		/notion\.so/i,
		/notion\.com/i,
		/trello\.com/i,
		/asana\.com/i,
		/monday\.com/i,
		/jira\./i,
		/atlassian\./i,
		/confluence\./i,
		/docs\.google\.com/i,
		/sheets\.google\.com/i,
		/slides\.google\.com/i,
		/drive\.google\.com/i,
		/calendar\.google\.com/i,
		/mail\.google\.com/i,
		/outlook\./i,
		/office\.com/i,
		/linkedin\.com/i,
		/zoom\.us/i,
		/meet\.google\.com/i,
		/teams\.microsoft\.com/i,
		/figma\.com/i,
		/canva\.com/i,
		/miro\.com/i,
		/vercel\.com/i,
		/netlify\.com/i,
		/heroku\.com/i,
		/digitalocean\.com/i,
		/aws\.amazon\.com/i,
		/console\.cloud\.google/i,
		/azure\.microsoft\.com/i,
		/codepen\.io/i,
		/jsfiddle\.net/i,
		/codesandbox\.io/i,
		/replit\.com/i,
		/npmjs\.com/i,
		/packagist\.org/i,
		/pypi\.org/i,
		/medium\.com/i,
		/dev\.to/i,
		/hashnode\.com/i,
		/smashingmagazine\.com/i,
		/css-tricks\.com/i,
		/alistapart\.com/i,
		/baeldung\.com/i,
		/theodinproject\.com/i,
		/docs\.aws\.amazon/i,
		/developers\.google/i,
		/learn\.microsoft/i,
		/docs\.docker/i,
		/coursera\.org/i,
		/udemy\.com/i,
		/skillshare\.com/i,
		/pluralsight\.com/i,
		/egghead\.io/i,
		/frontendmasters\.com/i,
		/w3schools\.com/i,
		/mdn\.mozilla/i,
		/developer\.mozilla/i,
		/freecodecamp\.org/i,
	],
	social: [
		/facebook\.com/i,
		/fb\.com/i,
		/fb\.watch/i,
		/twitter\.com/i,
		/x\.com/i,
		/instagram\.com/i,
		/snapchat\.com/i,
		/reddit\.com/i,
		/old\.reddit/i,
		/redd\.it/i,
		/discord\.com/i,
		/discord\.gg/i,
		/discordapp\.com/i,
		/telegram\.org/i,
		/t\.me/i,
		/web\.telegram/i,
		/whatsapp\.com/i,
		/web\.whatsapp/i,
		/messenger\.com/i,
		/pinterest\.com/i,
		/pin\.it/i,
		/tumblr\.com/i,
		/threads\.net/i,
		/mastodon\./i,
		/mstdn\./i,
		/bsky\.app/i,
		/quora\.com/i,
		/weibo\.com/i,
		/weibo\.cn/i,
		/douyin\.com/i,
		/kuaishou\.com/i,
		/line\.me/i,
		/kakaotalk\.com/i,
		/naver\.com/i,
		/band\.us/i,
		/clubhouse\.com/i,
		/nextdoor\.com/i,
		/meetup\.com/i,
		/eventbrite\.com/i,
		/producthunt\.com/i,
		/linktr\.ee/i,
		/linktree\.com/i,
		/bio\.link/i,
		/beacons\.ai/i,
		/stan\.store/i,
		/hackernews\.com/i,
		/news\.ycombinator/i,
		/lobste\.rs/i,
		/slashdot\.org/i,
		/digg\.com/i,
		/voat\.co/i,
		/lemmy\./i,
		/kbin\./i,
		/cohost\.org/i,
	],
	entertainment: [
		/9gag\.com/i,
		/imgur\.com/i,
		/i\.imgur/i,
		/giphy\.com/i,
		/tenor\.com/i,
		/gfycat\.com/i,
		/streamable\.com/i,
		/rottentomatoes\.com/i,
		/imdb\.com/i,
		/metacritic\.com/i,
		/letterboxd\.com/i,
		/trakt\.tv/i,
		/justwatch\.com/i,
		/thetvdb\.com/i,
		/themoviedb\.org/i,
		/myanimelist\.net/i,
		/anilist\.co/i,
		/kitsu\.io/i,
		/anime-planet\.com/i,
		/webtoons\.com/i,
		/tapas\.io/i,
		/mangadex\.org/i,
		/mangaplus\.shueisha/i,
		/comixology\.com/i,
		/marvel\.com/i,
		/dc\.com/i,
	],
	movies: [
		/netflix\.com/i,
		/hbo\.com/i,
		/hbomax\.com/i,
		/max\.com/i,
		/hbonow\.com/i,
		/hbogo\.com/i,
		/uakino\.best/i,
		/megogo\.net/i,
		/sweet\.tv/i,
		/oll\.tv/i,
		/takflix\.com/i,
		/kyivstar\.tv/i,
		/volia\.tv/i,
	],
	video: [
		/youtube\.com/i,
		/youtu\.be/i,
		/hulu\.com/i,
		/amazon\.(com|co\.uk|ca)\/primevideo/i,
		/primevideo\.com/i,
		/disneyplus\.com/i,
		/peacocktv\.com/i,
		/paramountplus\.com/i,
		/appletv\.apple\.com/i,
		/twitch\.tv/i,
		/vimeo\.com/i,
		/dailymotion\.com/i,
		/tiktok\.com/i,
		/tv\.tiktok/i,
	],
	news: [
		/nytimes\.com/i,
		/bbc\.com/i,
		/cnn\.com/i,
		/foxnews\.com/i,
		/theguardian\.com/i,
		/reuters\.com/i,
		/apnews\.com/i,
		/bloomberg\.com/i,
		/wsj\.com/i,
		/ft\.com/i,
		/economist\.com/i,
		/forbes\.com/i,
		/businessinsider\.com/i,
		/techcrunch\.com/i,
		/wired\.com/i,
		/theverge\.com/i,
		/engadget\.com/i,
		/arstechnica\.com/i,
		/venturebeat\.com/i,
		/mashable\.com/i,
		/thenextweb\.com/i,
		/axios\.com/i,
		/newyorker\.com/i,
		/time\.com/i,
		/nationalgeographic\.com/i,
		/history\.com/i,
		/sciencedaily\.com/i,
		/newscientist\.com/i,
		/sciencemag\.org/i,
		/nature\.com/i,
		/theatlantic\.com/i,
		/slate\.com/i,
		/vox\.com/i,
		/npr\.org/i,
		/aljazeera\.com/i,
		/politico\.com/i,
		/financialpost\.com/i,
		/globeandmail\.com/i,
		/toronto\.com/i,
		/cbc\.ca/i,
	],
	finance: [
		/paypal\.com/i,
		/stripe\.com/i,
		/wise\.com/i,
		/revolut\.com/i,
		/monzo\.com/i,
		/chase\.com/i,
		/bankofamerica\.com/i,
		/wellsfargo\.com/i,
		/citibank\.com/i,
		/americanexpress\.com/i,
		/discover\.com/i,
		/capitalone\.com/i,
		/coinbase\.com/i,
		/binance\.com/i,
		/kraken\.com/i,
		/robinhood\.com/i,
		/fidelity\.com/i,
		/vanguard\.com/i,
		/schwab\.com/i,
		/tdameritrade\.com/i,
		/e*trade\.com/i,
		/etrade\.com/i,
	],
	shopping: [
		/amazon\.com/i,
		/ebay\.com/i,
		/etsy\.com/i,
		/walmart\.com/i,
		/target\.com/i,
		/bestbuy\.com/i,
		/home depot\.com/i,
		/homedepot\.com/i,
		/lowes\.com/i,
		/ikea\.com/i,
		/wayfair\.com/i,
		/aliexpress\.com/i,
		/alibaba\.com/i,
		/taobao\.com/i,
		/shopify\.com/i,
		/shop\.app/i,
		/amazon\.co\.uk/i,
		/amazon\.ca/i,
		/amazon\.de/i,
		/amazon\.fr/i,
		/amazon\.it/i,
		/amazon\.es/i,
		/amazon\.jp/i,
		/amazon\.com\.au/i,
		/ebay\.co\.uk/i,
		/ebay\.de/i,
		/ebay\.fr/i,
		/ebay\.it/i,
		/ebay\.es/i,
		/ebay\.com\.au/i,
		/ebay\.ca/i,
		/etsy\.com/i,
		/walmart\.ca/i,
		/target\.ca/i,
		/olx\.ua/i,
		/olx\.com/i,
		/olx\.pl/i,
		/rozetka\.ua/i,
		/rozetka\.com\.ua/i,
	],
	education: [
		/coursera\.org/i,
		/edx\.org/i,
		/udacity\.com/i,
		/khanacademy\.org/i,
		/ocw\.mit\.edu/i,
		/stanford\.edu/i,
		/harvard\.edu/i,
		/berkeley\.edu/i,
		/mit\.edu/i,
		/ox\.ac\.uk/i,
		/cam\.ac\.uk/i,
		/edx\.org/i,
		/udemy\.com/i,
		/udacity\.com/i,
		/pluralsight\.com/i,
		/skillshare\.com/i,
		/lynda\.com/i,
		/linkedin\.com\/learning/i,
		/codecademy\.com/i,
		/freecodecamp\.org/i,
		/w3schools\.com/i,
		/mdn\.mozilla/i,
	],
	productivity: [
		/notion\.so/i,
		/evernote\.com/i,
		/todoist\.com/i,
		/trello\.com/i,
		/asana\.com/i,
		/monday\.com/i,
		/airtable\.com/i,
		/miro\.com/i,
		/coda\.io/i,
		/canva\.com/i,
	],
	gaming: [
		/steamcommunity\.com/i,
		/store\.steampowered\.com/i,
		/steampowered\.com/i,
		/epicgames\.com/i,
		/gog\.com/i,
		/battle\.net/i,
		/riotgames\.com/i,
		/ea\.com/i,
		/ubisoft\.com/i,
		/playstation\.com/i,
		/xbox\.com/i,
		/nintendo\.com/i,
		/roblox\.com/i,
		/minecraft\.net/i,
		/twitch\.tv/i,
		/discord\.gg/i,
		/itch\.io/i,
		/kongregate\.com/i,
	],
	health: [
		/webmd\.com/i,
		/mayoclinic\.org/i,
		/healthline\.com/i,
		/nih\.gov/i,
		/cdc\.gov/i,
		/who\.int/i,
		/fitness\.com/i,
		/myfitnesspal\.com/i,
		/strava\.com/i,
		/headspace\.com/i,
		/calm\.com/i,
		/betterhelp\.com/i,
	],
	travel: [
		/booking\.com/i,
		/airbnb\.com/i,
		/expedia\.com/i,
		/skyscanner\.com/i,
		/tripadvisor\.com/i,
		/kayak\.com/i,
		/travelocity\.com/i,
		/orbitz\.com/i,
		/priceline\.com/i,
		/uber\.com/i,
		/lyft\.com/i,
		/maps\.google\.com/i,
		/google\.com\/maps/i,
	],
	music: [
		/spotify\.com/i,
		/soundcloud\.com/i,
		/bandcamp\.com/i,
		/pandora\.com/i,
		/music\.apple\.com/i,
		/youtube\.com\/music/i,
		/tidal\.com/i,
		/deezer\.com/i,
		/last\.fm/i,
	],
	sports: [/espn\.com/i, /nfl\.com/i, /nba\.com/i, /mlb\.com/i, /nhl\.com/i, /fifa\.com/i, /uefa\.com/i, /olympics\.com/i],
	food: [
		/allrecipes\.com/i,
		/foodnetwork\.com/i,
		/epicurious\.com/i,
		/seriouseats\.com/i,
		/bonappetit\.com/i,
		/uber eats\.com/i,
		/ubereats\.com/i,
		/doordash\.com/i,
		/grubhub\.com/i,
	],
	adult: [
		/pornhub\.com/i,
		/xvideos\.com/i,
		/xhamster\.com/i,
		/redtube\.com/i,
		/youporn\.com/i,
		/xnxx\.com/i,
		/xnxx\.com/i,
		/hentai\.org/i,
		/f95zone\.to/i,
		/e-hentai\.org/i,
		/nhentai\.net/i,
		/onlyfans\.com/i,
		/fansly\.com/i,
		/patreon\.com/i,
	],
	security: [
		/owasp\.org/i,
		/sans\.org/i,
		/mitre\.org/i,
		/attack\.mitre/i,
		/virustotal\.com/i,
		/hybrid-analysis\.com/i,
		/any\.run/i,
		/urlscan\.io/i,
		/shodan\.io/i,
		/exploit-db\.com/i,
		/hackthebox\.com/i,
		/tryhackme\.com/i,
		/pentesterlab\.com/i,
		/portswigger\.net/i,
		/burpsuite\.net/i,
		/metasploit\.com/i,
		/nmap\.org/i,
		/wireshark\.org/i,
		/snyk\.io/i,
		/sonarqube\.org/i,
		/dependabot\.com/i,
	],
};

/**
 * URL path patterns for news/blog/article detection
 * These patterns match against the full URL path
 */
const NEWS_PATH_PATTERNS = [
	// Blog patterns
	/\/blog\//i,
	/\/blogs\//i,
	/\/weblog\//i,

	// News patterns
	/\/news\//i,
	/\/news-/i,
	/\/breaking\//i,
	/\/latest\//i,
	/\/headlines\//i,
	/\/press\//i,
	/\/press-release/i,
	/\/media\//i,
	/\/newsroom\//i,

	// Article patterns
	/\/article\//i,
	/\/articles\//i,
	/\/story\//i,
	/\/stories\//i,
	/\/post\//i,
	/\/posts\//i,
	/\/read\//i,

	// Release/Update patterns
	/\/releases\//i,
	/\/release\//i,
	/\/changelog\//i,
	/\/updates\//i,
	/\/update\//i,
	/\/whats-new/i,
	/\/announcements?\//i,

	// Editorial patterns
	/\/editorial\//i,
	/\/opinion\//i,
	/\/perspectives?\//i,
	/\/insights?\//i,
	/\/analysis\//i,
	/\/reports?\//i,
	/\/review\//i,
	/\/reviews\//i,

	// Publication patterns
	/\/publication\//i,
	/\/publications\//i,
	/\/journal\//i,
	/\/magazine\//i,
	/\/digest\//i,

	// Date-based article URLs (common pattern: /2024/01/article-name)
	/\/\d{4}\/\d{1,2}\/[a-z0-9-]+/i,

	// Content type indicators
	/\/content\//i,
	/\/featured\//i,
	/\/trending\//i,
	/\/popular\//i,
	/\/spotlight\//i,

	// Tech/Dev specific
	/\/devblog\//i,
	/\/engineering\//i,
	/\/tech-blog\//i,
	/\/developer-blog\//i,

	// Company blog patterns
	/\/company-news\//i,
	/\/corporate\//i,
	/\/about\/news/i,

	// Newsletter patterns
	/\/newsletter\//i,
	/\/subscribe\//i,
];

/**
 * Check if URL path matches news/blog patterns
 * @param {string} url - Full URL to check
 * @returns {boolean}
 */
function isNewsPath(url) {
	try {
		const urlObj = new URL(url);
		const fullPath = urlObj.pathname + urlObj.search;

		for (const pattern of NEWS_PATH_PATTERNS) {
			if (pattern.test(fullPath)) {
				return true;
			}
		}
		return false;
	} catch {
		return false;
	}
}

function ruleMatches(rule, domain, url) {
	if (!rule || !rule.pattern || !rule.category) return false;
	const pattern = String(rule.pattern).trim();
	if (!pattern) return false;

	const targetDomain = (domain || '').toLowerCase();
	const targetUrl = (url || '').toLowerCase();

	if (pattern.startsWith('/') && pattern.endsWith('/') && pattern.length > 2) {
		try {
			const re = new RegExp(pattern.slice(1, -1), 'i');
			return re.test(domain) || (url && re.test(url));
		} catch {
			return false;
		}
	}

	const needle = pattern.toLowerCase();
	return targetDomain.includes(needle) || targetUrl.includes(needle);
}

/**
 * Categorize a domain (enhanced with path detection)
 * @param {string} domain - Domain to categorize
 * @param {string} url - Full URL for path-based detection
 * @returns {string} Category name
 */
function categorize(domain, url = '') {
	// Custom rules take priority
	for (const rule of customCategoryRules) {
		if (ruleMatches(rule, domain, url)) {
			return rule.category;
		}
	}

	// First check domain-based rules
	for (const [category, patterns] of Object.entries(CATEGORY_RULES)) {
		for (const pattern of patterns) {
			if (pattern.test(domain)) {
				return category;
			}
		}
	}

	// Check URL path for news/blog patterns (for sites not in domain list)
	if (url && isNewsPath(url)) {
		return 'news';
	}

	return 'other';
}
